In [1]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time

In [3]:
URL = "https://www.indeed.com/jobs?q=data+scientist+%2420%2C000&l=New+York&start=10"
#conducting a request of the stated URL above:
page = requests.get(URL)
#specifying a desired format of “page” using the html parser - this allows python to read the various components of the page, rather than treating it as one long string.
soup = BeautifulSoup(page.text, "html.parser")

In [6]:
def extract_job_title_from_result(soup): 
    jobs = []
    for div in soup.find_all(name="div", attrs={"class":"row"}):
        for a in div.find_all(name="a", attrs={"data-tn-element":"jobTitle"}):
            jobs.append(a["title"])
    return(jobs)
extract_job_title_from_result(soup)

['Data Scientist, Analytics- Instagram-Family Stories',
 'Data Scientist',
 'Data Scientist',
 'Junior Data Scientist',
 'Data Science Analyst',
 'Data Scientist',
 'Data Scientist',
 'CI Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Programmer/Data Scientist',
 'Data Scientist/Engineer (SAS, R code, Python & Sql (Open to remote Workers))',
 'Data Scientist, Kinship - NYC/Portland',
 'Data Scientist, Analytics - Recruiting Products']

In [10]:
def extract_company_from_result(soup): 
    companies = []
    for div in soup.find_all(name="div", attrs={"class":"row"}):
        company = div.find_all(name="span", attrs={"class":"company"})
        if len(company) > 0:
            for b in company:
                companies.append(b.text.strip())
        else:
            sec_try = div.find_all(name="span", attrs={"class":"result-link-source"})
            for span in sec_try:
                companies.append(span.text.strip())
    return(companies)
 
extract_company_from_result(soup)

['Facebook',
 'Pearson',
 'Ohi',
 'Decode_M',
 'AETNA',
 'Unite Us',
 'RISIRISA',
 'Novelis',
 'Booz Allen Hamilton',
 'Catholic Health Services of Long Island',
 '1-800-Flowers',
 'New York University',
 'Medidata Solutions',
 'Mars',
 'Facebook']

In [12]:
def extract_location_from_result(soup): 
    locations = []
    spans = soup.findAll("span", attrs={"class": "location"})
    for span in spans:
        locations.append(span.text)
    return(locations)
extract_location_from_result(soup)

['New York, NY',
 'Albany, NY',
 'New York, NY',
 'New York, NY',
 'New York, NY 10016 (Murray Hill area)',
 'New York, NY 10007 (Tribeca area)',
 'New York, NY',
 'Oswego, NY 13126',
 'New York, NY 10036 (Garment District area)',
 'Melville, NY',
 'Carle Place, NY 11514',
 'New York, NY 10012 (Greenwich Village area)',
 'New York, NY 10003 (Flatiron District area)',
 'New York, NY 10001 (Chelsea area)',
 'New York, NY']

In [20]:
def extract_summary_from_result(soup): 
    summaries = []
    spans = soup.findAll("div", attrs={"class": "summary"})
    for span in spans:
        summaries.append(span.text.strip())
    return(summaries)
extract_summary_from_result(soup)

['5+ years of hands-on data science experience.\nDetermine ways to use data as a strategic asset in product development Technical Execution:',
 'Understands and prepares data for analysis by applying knowledge of data sources and how they are gathered, stored and retrieved as well as manipulating large…',
 'Bring best in class data-engineering and into the organization to enable the engineering team to work effectively at speed with high quality.',
 'Transform data and insights into compelling and creative visualizations.\nYou have experience using applied statistics, and you’re comfortable working with…',
 'Familiarity with big data concepts.\nRecommends additional sources of data for improvements.\nUses data visualization techniques to effectively communicate…',
 'Experience with healthcare data and analytics is preferred.\nThis role provides a unique opportunity to be part of the founding team focused on data expansion…',
 'Experience with a range of data science techniques including clustering, machine learning, natural language processing, and network analysis.',
 'Understanding of various data structures such as .\nAt Novelis, we have found that having operations domain and process expertise in the data that is being…',
 'You’ll mentor teammates, conduct data analysis and modeling, design data-driven solutions and approaches for clients, and use the right combination of tools and…',
 'Focusing on all aspects of data science, including data gathering and.\nWith the multi-disciplined business analysts, technical analysts, data scientists.',
 'This individual will manage one or more analysts and focus on customer-level advanced analytics for the direct-to-consumer and business-to-business channels.',
 'Preprocess data, and produce meaningful data visualizations.\nPursue research featuring the innovative use of social media data to study politics and political.',
 '5+ years professional experience as a data scientist, data engineer, data analyst, or related role.\nCollaborate with data scientists, business leaders and cross…',
 '4+ years’ experience in a data science role handling varied and complex data.\nVaried technical experience in delivering statistical analytics, data science and…',
 'Apply your expertise in quantitative analysis, data mining, and the presentation of data to see beyond the numbers and understand how our users interact with…']

In [44]:
max_results_per_city = 100
#city_set = ["New+York","Chicago","San+Francisco", "Austin", "Seattle", "Los+Angeles", "Philadelphia", "Atlanta", "Dallas", "Pittsburgh", "Portland", "Phoenix", "Denver", "Houston", "Miami", "Washington+DC", "Boulder"]
city_set = ["New+York"]
columns = ["city", "job_title", "company_name", "location", "summary","Date"]
sample_df = pd.DataFrame(columns = columns)

In [47]:

for city in city_set:
    for start in range(0, max_results_per_city, 1):
        page = requests.get("https://www.indeed.com/jobs?q=data+scientist+$20,000&l=" + str(city) + "&start=" + str(start))
        time.sleep(1)  #ensuring at least 1 second between page grabs
        soup = BeautifulSoup(page.text, "lxml", from_encoding="utf-8")
        for div in soup.find_all(name="div", attrs={"class":"row"}): 
    #specifying row num for index of job posting in dataframe
            num = (len(sample_df) + 1) 
    #creating an empty list to hold the data for each posting
            job_post = [] 
    #append city name
            job_post.append(city) 
    #grabbing job title
            for a in div.find_all(name="a", attrs={"data-tn-element":"jobTitle"}):
                job_post.append(a["title"]) 
    #grabbing company name
            company = div.find_all(name="span", attrs={"class":"company"}) 
            if len(company) > 0: 
                for b in company:
                    job_post.append(b.text.strip()) 
            else: 
                sec_try = div.find_all(name="span", attrs={"class":"result-link-source"})
                for span in sec_try:
                    job_post.append(span.text) 
    #grabbing location name
            c = div.findAll("span", attrs={"class": "location"}) 
            for span in c: 
                job_post.append(span.text) 
    #grabbing summary text
            d = div.findAll("div", attrs={"class": "summary"}) 
            for span in d:
                job_post.append(span.text.strip()) 
            date = div.findAll("span", attrs={"class": "date"}) 
            for span in date:
                job_post.append(span.text.strip()) 
    #appending list of job post info to dataframe at index num
        #print(job_post)
        sample_df.loc[num] = job_post

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:146: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

In [48]:
sample_df

,city,job_title,company_name,location,summary,Date
1,New+York,"Data Scientist, Analytics",Bowery Farming,"New York, NY 10011 (Flatiron District area)",Collaborate on the design and creation of data...,26 days ago
2,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
3,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
4,New+York,"Data Scientist, Recommendations",Tapestry,"New York, NY 10011 (Greenwich Village area)","Collect, clean, integrate, analyze, and visual...",30+ days ago
5,New+York,"Data Analyst Programmer, Multiphoton Core",University of Rochester,"Rochester, NY",Interacts closely and collaborates with other ...,4 days ago
6,New+York,Data Scientist Associate Sr (DADS06) BTB - LEG...,"JPMorgan Chase Bank, N.A.","New York, NY","Be a data storyteller, deliver practical data ...",15 days ago
7,New+York,STATISTICAL ASSISTANT,UTOFUN,"Manhattan, NY",Maintain and enter a large dataset of real est...,30+ days ago
8,New+York,Investment Analyst Intern,KKI Capital,"New York, NY",Conduct due diligence on ongoing cases.\nRespo...,30+ days ago
9,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
10,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
11,New+York,"Data Scientist, Analytics",Bowery Farming,"New York, NY 10011 (Flatiron District area)",Collaborate on the design and creation of data...,26 days ago
12,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
13,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
14,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
15,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
16,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
17,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
18,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
19,New+York,Data Scientist,RISIRISA,"New York, NY",Experience with a range of data science techni...,30+ days ago
20,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
21,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
22,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
23,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
24,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
25,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
26,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
27,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
28,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
29,New+York,Data Science Engineer,TMP Worldwide,"New York, NY",When the world throws technology challenges at...,Today
30,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
...,...,...,...,...,...,...
81,New+York,Senior Data Scientist,Braavo Capital,"New York, NY 10001 (Chelsea area)","Using data, integrations, and automation, Braa...",30+ days ago
82,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
83,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
84,New+York,"Senior / Data Scientist, Ads and Messaging R&D",Spotify,"New York, NY 10011 (Flatiron District area)",Build lasting solutions to surface critical da...,30+ days ago
85,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
86,New+York,Data Scientist,A Place for Mom,"New York, NY 10002 (Lower East Side area)",Operate and maintain tools that combine dispar...,30+ days ago
87,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
88,New+York,"Senior / Data Scientist, Ads and Messaging R&D",Spotify,"New York, NY 10011 (Flatiron District area)",Build lasting solutions to surface critical da...,30+ days ago
89,New+York,Quantum Data Scientist- Industrial Discrete Se...,IBM,"Yorktown Heights, NY",2+ years of data engineering and data science ...,15 days ago
90,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
91,New+York,"Senior / Data Scientist, Ads and Messaging R&D",Spotify,"New York, NY 10011 (Flatiron District area)",Build lasting solutions to surface critical da...,30+ days ago
92,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
93,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
94,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
95,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
96,New+York,Senior Analyst - Data Science,American Express,"New York, NY",Develop predictive modeling that incorporates ...,4 days ago
97,New+York,Research Analyst (Data Science),APCO Worldwide,"New York, NY",The data science Research Analyst will support...,29 days ago
98,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
99,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
100,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
101,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
102,New+York,"Data Scientist, Senior",Booz Allen Hamilton,"Rome, NY 13441",Experience with building complex data extracti...,30+ days ago
103,New+York,Data Scientist,The Powerline Group,"Port Jefferson Station, NY 11776",Determining the correct data sets and variable...,30+ days ago
104,New+York,"Data Scientist, Senior",Booz Allen Hamilton,"Rome, NY 13441",Experience with building complex data extracti...,30+ days ago
105,New+York,Data Analyst Bassett Health Plan,Bassett Medical Center,"Cooperstown, NY 13326",Ability to organize and assess various statist...,30+ days ago
106,New+York,Data Scientist,The Powerline Group,"Port Jefferson Station, NY 11776",Determining the correct data sets and variable...,30+ days ago
107,New+York,Data Scientist,The Powerline Group,"Port Jefferson Station, NY 11776",Determining the correct data sets and variable...,30+ days ago
108,New+York,Senior Data Scientist,Alldus,"New York, NY",Experience working with large data sets.\nDemo...,15 days ago
109,New+York,Data Scientist,The Powerline Group,"Port Jefferson Station, NY 11776",Determining the correct data sets and variable...,30+ days ago
110,New+York,"Data Scientist, Senior",Booz Allen Hamilton,"Rome, NY 13441",Experience with building complex data extracti...,30+ days ago

In [49]:
df = sample_df.drop_duplicates()

In [50]:
df.shape

(29, 6)

In [51]:
df

,city,job_title,company_name,location,summary,Date
1,New+York,"Data Scientist, Analytics",Bowery Farming,"New York, NY 10011 (Flatiron District area)",Collaborate on the design and creation of data...,26 days ago
2,New+York,"Data Scientist, Analytics - Recruiting Products",Facebook,"New York, NY","Apply your expertise in quantitative analysis,...",30+ days ago
4,New+York,"Data Scientist, Recommendations",Tapestry,"New York, NY 10011 (Greenwich Village area)","Collect, clean, integrate, analyze, and visual...",30+ days ago
5,New+York,"Data Analyst Programmer, Multiphoton Core",University of Rochester,"Rochester, NY",Interacts closely and collaborates with other ...,4 days ago
6,New+York,Data Scientist Associate Sr (DADS06) BTB - LEG...,"JPMorgan Chase Bank, N.A.","New York, NY","Be a data storyteller, deliver practical data ...",15 days ago
7,New+York,STATISTICAL ASSISTANT,UTOFUN,"Manhattan, NY",Maintain and enter a large dataset of real est...,30+ days ago
8,New+York,Investment Analyst Intern,KKI Capital,"New York, NY",Conduct due diligence on ongoing cases.\nRespo...,30+ days ago
9,New+York,Data Scientist - Investment Research,"Two Sigma Investments, LLC.","New York, NY",Contribute to data sourcing strategy across mu...,30+ days ago
10,New+York,"Staff Data Scientist, Analytics",Etsy,"Brooklyn, NY 11201",6+ years experience as a data scientist or dat...,30+ days ago
12,New+York,Data Scientist,Unite Us,"New York, NY 10007 (Tribeca area)",Experience with healthcare data and analytics ...,5 days ago
19,New+York,Data Scientist,RISIRISA,"New York, NY",Experience with a range of data science techni...,30+ days ago
29,New+York,Data Science Engineer,TMP Worldwide,"New York, NY",When the world throws technology challenges at...,Today
40,New+York,Data Scientist for Justice,Measures for Justice,"Rochester, NY",Background in quantitative criminal justice da...,30+ days ago
41,New+York,Data Scientist,DataDog,"New York, NY",Have previously worked with cloud provider bil...,30+ days ago
46,New+York,People Analytics Data Scientist,"D. E. Shaw & Co., L.P.","New York, NY 10036 (Midtown area)","Experience building ETLs, manipulating data at...",30+ days ago
64,New+York,"Data Science Analyst, UNDP/BPPS Effectiveness ...",United Nations Development Programme (UNDP),"New York, NY 10017 (Turtle Bay area)",Prepare a conceptual data model for data platf...,2 days ago
66,New+York,"VP, Data Science",7Park Data,"New York, NY 10011 (Chelsea area)",Review internal and external analytical techni...,4 days ago
72,New+York,Senior Data Scientist,Braavo Capital,"New York, NY 10001 (Chelsea area)","Using data, integrations, and automation, Braa...",30+ days ago
73,New+York,"Data Scientist, Acorn AI Labs",Medidata Solutions,"New York, NY 10003 (Flatiron District area)",Our team is composed of over 40 PhD/Masters st...,30+ days ago
76,New+York,Senior Data Analyst,Bounce Exchange,"New York, NY 10013 (SoHo area)",Reduce the current cost of data infrastructure...,30+ days ago
84,New+York,"Senior / Data Scientist, Ads and Messaging R&D",Spotify,"New York, NY 10011 (Flatiron District area)",Build lasting solutions to surface critical da...,30+ days ago
86,New+York,Data Scientist,A Place for Mom,"New York, NY 10002 (Lower East Side area)",Operate and maintain tools that combine dispar...,30+ days ago
89,New+York,Quantum Data Scientist- Industrial Discrete Se...,IBM,"Yorktown Heights, NY",2+ years of data engineering and data science ...,15 days ago
96,New+York,Senior Analyst - Data Science,American Express,"New York, NY",Develop predictive modeling that incorporates ...,4 days ago
97,New+York,Research Analyst (Data Science),APCO Worldwide,"New York, NY",The data science Research Analyst will support...,29 days ago
102,New+York,"Data Scientist, Senior",Booz Allen Hamilton,"Rome, NY 13441",Experience with building complex data extracti...,30+ days ago
103,New+York,Data Scientist,The Powerline Group,"Port Jefferson Station, NY 11776",Determining the correct data sets and variable...,30+ days ago
105,New+York,Data Analyst Bassett Health Plan,Bassett Medical Center,"Cooperstown, NY 13326",Ability to organize and assess various statist...,30+ days ago
108,New+York,Senior Data Scientist,Alldus,"New York, NY",Experience working with large data sets.\nDemo...,15 days ago

In [77]:
keyword = "data scientist,$10000, Inter"
where = "New York"
remote = 1
formage = 14
salary = "$20000"
jobType = "fulltime"
location = ""
company = ""
experience = "" 
URL = "https://www.indeed.com/jobs?"

In [81]:
if salary != "":
    if "$" in keyword:
        print("yes")
        keyword = keyword[:keyword.find("$")] + " "+salary
    else:
        keyword = keyword+"+"+salary
keyword = keyword.replace(" ","+")
keyword = keyword.replace(",", "%2C")
keyword = keyword.replace("/", "%2F")
if where == "":
    if location != "":
        where = location
        location = ""
where = where.replace(" ","+")
where = where.replace(",", "%2C")
where = where.replace("/", "%2F")
URL = URL+"&q="+keyword+"&l="+where
URL

yes

'https://www.indeed.com/jobs?&q=data+scientist%2C++$20000&l=New+York'

In [84]:
if(remote ==1):
    URL += "&remotejob=1"

if(formage > 0):
    URL += "&fromage="+str(formage)

if(jobType != ""):
    URL+= "&jt="+jobType

if(experience != ""):
    URL += "&explvl=" +experience

In [85]:
URL

'https://www.indeed.com/jobs?&q=data+scientist%2C++$20000&l=New+York&remotejob=1&remotejob=1&fromage=14&jt=fulltime'

In [97]:
def getJobs(URL, max_jobs):
    city_set = [1]
    columns = ["city", "job_title", "company_name", "location", "summary","Date"]
    sample_df = pd.DataFrame(columns = columns)
    for city in city_set:
        for start in range(0, max_jobs, 1):
            page = requests.get(URL) #+ "&start=" + str(start)
            time.sleep(1)  #ensuring at least 1 second between page grabs
            soup = BeautifulSoup(page.text, "lxml", from_encoding="utf-8")
            for div in soup.find_all(name="div", attrs={"class":"row"}): 
                num = (len(sample_df) + 1) 
                job_post = [] 
                job_post.append(city) 
                for a in div.find_all(name="a", attrs={"data-tn-element":"jobTitle"}):
                    job_post.append(a["title"]) 
                company = div.find_all(name="span", attrs={"class":"company"}) 
                if len(company) > 0: 
                    for b in company:
                        job_post.append(b.text.strip()) 
                else: 
                    sec_try = div.find_all(name="span", attrs={"class":"result-link-source"})
                    for span in sec_try:
                        job_post.append(span.text) 
                c = div.findAll("span", attrs={"class": "location"}) 
                for span in c: 
                    job_post.append(span.text) 
                d = div.findAll("div", attrs={"class": "summary"}) 
                for span in d:
                    job_post.append(span.text.strip()) 
                date = div.findAll("span", attrs={"class": "date"}) 
                for span in date:
                    job_post.append(span.text.strip()) 
            sample_df.loc[num] = job_post
    return sample_df

In [98]:
getJobs(URL,1)

C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py:146: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

,city,job_title,company_name,location,summary,Date
1,1,Enterprise Solutions Engineer - Southeast,Verkada,"Town of Southeast, NY",This individual will partner directly with the...,4 days ago